### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by jonavm** [valinyourarea/WS_ghandi#11]
Objetivo: Proveer una documentación completa y ejemplos de cómo usar el scraper específicamente para el sitio web de Gandhi, facilitando su uso y comprensión.

Tareas:

Documentación Exhaustiva: Redactar documentación detallada para la clase Scraper, incluyendo descripciones de métodos, parámetros y formatos de salida.
Instrucciones de Uso: Escribir una guía paso a paso sobre cómo configurar el entorno, instalar dependencias y ejecutar el scraper para obtener datos de Gandhi.
Ejemplos Prácticos: Crear ejemplos de código que muestren cómo utilizar el scraper para diferentes categorías o páginas de libros en el sitio web de Gandhi.

**Comment by valinyourarea** [comment]
ya documente los dos códigos de webscraping que tenemos hasta ahora, quedo al pendiente de cualquier duda o corrección.
