### ISSUE TITLE
scraper_base

### ISSUE THREAD

**Issue by valinyourarea** [valinyourarea/WS_ghandi#5]
vas a hacer un scraper que contenga:

Importación de Bibliotecas:
Importa las bibliotecas necesarias, como pandas, BeautifulSoup, requests, mysql.connector, y time.

Definición de Encabezados:
Define un diccionario de encabezados HTTP para simular una solicitud de navegador.

Configuración de Búsqueda:
Establece la cadena de búsqueda (por ejemplo, 'Harry') y una lista vacía para almacenar información sobre libros.

Bucle Principal:
Utiliza un bucle para iterar a través de múltiples páginas de resultados (por ejemplo, 1 a 19).

Construcción de la URL de Búsqueda:
Construye la URL de búsqueda utilizando el número de página y la cadena de búsqueda.

Solicitud GET y Análisis HTML:
Realiza una solicitud GET a la URL utilizando los encabezados definidos y analiza el contenido HTML de la página con BeautifulSoup.

Extracción de Información:
Encuentra elementos HTML que contienen información sobre libros y extrae detalles como título, autor, precio y portada.

Almacenamiento de Datos en una Lista:
Crea un diccionario para cada libro y agrégalo a la lista de libros.

Creación de un DataFrame y Guardado en CSV:
Utiliza Pandas para convertir la lista de diccionarios en un DataFrame y guarda los resultados en un archivo CSV.

Conexión a MySQL y Creación de Tabla:
Establece una conexión a MySQL con las credenciales correctas y crea una tabla si no existe.

Inserción de Datos en MySQL:
Utiliza un bucle para insertar los datos de los libros en la tabla MySQL.

Confirmación y Cierre de Conexión MySQL:
Confirma los cambios en la base de datos y cierra la conexión a MySQL.

Medición del Tiempo de Ejecución:
Registra el tiempo de ejecución del script y imprímelo en la consola.

**Comment by IsaiasLT** [comment]
He hecho el codigo, funciona y recopila algunos datos al igual que almacenarlos en un localhost con MySQL, sin embargo, falta ciertos puntos como:

Recopilar link de cada producto
Pasar a clases
