### ISSUE TITLE
scraper_Recopilar link de cada producto

### ISSUE THREAD

**Issue by valinyourarea** [valinyourarea/WS_ghandi#6]
haz que el scraper recopile el url de cada producto (debe ser el mismo scraper que Isaias ya hizo, checa su branch, ahí está en documento)
puedes seguir esta serie de pasos para guiarte. (solo es una guía, tu puedes agregar lo quitar lo que consideres necesario) 

Modificar la Estructura de Datos:
Agrega una nueva clave al diccionario book_data para almacenar el URL del libro. Puedes obtener el URL directamente del enlace que rodea al título o cualquier otro elemento único.

Actualización de la Extracción de Información:
Dentro del bucle que itera sobre los productos, encuentra el elemento HTML que contiene el enlace del libro y extrae la URL correspondiente.
ej:
link_element = product.find('a', class_='product-item-link')
link = link_element['href'] if link_element else None

Almacenamiento del URL en el Diccionario:
Agrega la URL extraída al diccionario book_data.
ej:
book_data = {
    'Title': title,
    'Author': author,
    'Price': price,
    'Cover': cover,
    'URL': link,
}

Modificación del DataFrame y CSV:
Asegúrate de que la nueva clave ('URL') se refleje en el DataFrame y, por lo tanto, en el archivo CSV.
ej:
df = pd.DataFrame(books, columns=['Title', 'Author', 'Price', 'Cover', 'URL'])
df.to_csv('books.csv', index=False)

Inserción de Datos en MySQL:
Asegúrate de que la tabla en MySQL también tenga una columna para almacenar los URLs.

ej: 
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(255),
    price VARCHAR(50),
    cover VARCHAR(255),
    url VARCHAR(255)
);

 Modifica el bucle de inserción para incluir el URL.
ej:
insert_query = "INSERT INTO books (title, author, price, cover, url) VALUES (%s, %s, %s, %s, %s)"

for book_data in books:
    data_tuple = (book_data['Title'], book_data['Author'], book_data['Price'], book_data['Cover'], book_data['URL'])
    cursor.execute(insert_query, data_tuple)
 
Descarga de URLs:
Después de la iteración sobre los productos y antes de pasar a la siguiente página, puedes agregar un código para descargar los URLs. Puedes usar bibliotecas como urllib o requests para descargar los contenidos de los URLs.
ej:
for book_data in books:
    url_to_download = book_data['URL']
    if url_to_download:
        # Agrega aquí el código para descargar el contenido del URL (por ejemplo, utilizando requests o urllib).

Guarda el contenido descargado si es necesario.

Estos pasos te permitirán agregar la funcionalidad de descargar URLs de libros a tu scraper. Asegúrate de ajustar el código según las especificaciones exactas de la estructura del sitio web de Gandhi y tus necesidades de descarga.

**Comment by damapech1** [comment]
El codigo ya puede generar los links de cada producto mediante la palabra que se escriba. Ahora falta pasarlo a clases.
