### ISSUE TITLE
Diseño de la Clase Scraper

### ISSUE THREAD

**Issue by jonavm** [valinyourarea/WS_ghandi#8]
Objetivo: Elaborar un diseño detallado para la clase Scraper que se especialice en extraer datos del sitio web, considerando su estructura y los datos específicos que queremos obtener.

Tareas:

Análisis del Sitio Web: Revisar el sitio web para identificar cómo se presentan los datos que queremos extraer (por ejemplo, títulos de libros, autores, precios).
Selección de Selectores CSS: Definir con precisión los selectores CSS que se utilizarán para extraer la información de los libros desde el sitio web de Gandhi.
Diseño de Métodos: Planificar los métodos de la clase Scraper, incluyendo:
Un método scrape(url) para extraer datos de una página específica.
Un método to_json() para procesar y organizar los datos extraídos en formato JSON.
Documentación del Diseño: Escribir una breve documentación de cada método, explicando su función y cómo se prevé su uso.

**Comment by IsaiasLT** [comment]
Yes, Boss
